import { PhotoItem } from '../types';

export const GALLERY_PHOTOS: PhotoItem[] = [
  // 01 — Lobby & Lounge (7 photos)
  {
    id: 'ext-01',
    filename: 'pexels-dropshado-31737842.jpg',
    src: '/photos/pexels-dropshado-31737842.jpg',
    category: 'lobby',
    title: { en: 'Architectural Facade at Dusk', vi: 'Mặt Tiền Kiến Trúc Lúc Hoàng Hôn' },
    description: { en: 'Multi-level minimalist architecture with glass balustrades and ambient lighting.', vi: 'Kiến trúc tối giản nhiều tầng với lan can kính và ánh sáng ấm áp.' },
    orientation: 'landscape',
    heroQuality: true,
    roomCardSuitable: false,
  },
  {
    id: 'ext-02',
    filename: 'pexels-dropshado-31737859.jpg',
    src: '/photos/pexels-dropshado-31737859.jpg',
    category: 'lobby',
    title: { en: 'Illuminated Night Courtyard', vi: 'Sân Vườn Ban Đêm Rực Rỡ' },
    description: { en: 'Manicured green lawn with linear LED footlights and wet stone reflections.', vi: 'Thảm cỏ xanh mượt với đèn hắt lối đi và nền đá tự nhiên.' },
    orientation: 'landscape',
    heroQuality: true,
    roomCardSuitable: false,
  },
  {
    id: 'ext-03',
    filename: 'pexels-dropshado-31737860.jpg',
    src: '/photos/pexels-dropshado-31737860.jpg',
    category: 'lobby',
    title: { en: 'Vertical Evening Architecture', vi: 'Góc Nhìn Kiến Trúc Đêm' },
    description: { en: 'Full elevation highlighting geometric glass framing and warm wooden soffits.', vi: 'Phối cảnh đứng tôn vinh nét kính hình học và trần gỗ ấm áp.' },
    orientation: 'portrait',
    heroQuality: true,
    roomCardSuitable: false,
  },
  {
    id: 'ent-01',
    filename: 'pexels-dropshado-31737861.jpg',
    src: '/photos/pexels-dropshado-31737861.jpg',
    category: 'lobby',
    title: { en: 'Grand Timber Entrance Portal', vi: 'Cổng Vào Gỗ Cổ Điển' },
    description: { en: 'Illuminated floating stone steps leading to a solid timber portal door.', vi: 'Bậc đá phát sáng dẫn vào cánh cửa gỗ khối sang trọng.' },
    orientation: 'portrait',
    heroQuality: true,
    roomCardSuitable: false,
  },
  {
    id: 'ent-02',
    filename: 'pexels-dropshado-31737862.jpg',
    src: '/photos/pexels-dropshado-31737862.jpg',
    category: 'lobby',
    title: { en: 'Arrival Steps & Greenery', vi: 'Lối Vào Sân Hiên Vườn' },
    description: { en: 'Warm sconce lights, sculpted stone planters, and wet terrazzo floor.', vi: 'Đèn tường ấm áp, chậu đá nghệ thuật và nền đá mài sang trọng.' },
    orientation: 'landscape',
    heroQuality: false,
    roomCardSuitable: false,
  },
  {
    id: 'lob-01',
    filename: 'pexels-misbaa-eri-426041722-36354488.jpg',
    src: '/photos/pexels-misbaa-eri-426041722-36354488.jpg',
    category: 'lobby',
    title: { en: 'Architectural Lounge & Hearth', vi: 'Sảnh Đón Tiếp & Lò Sưởi' },
    description: { en: 'Double-height lounge featuring grid pendant lamps, velvet seating, and timber niches.', vi: 'Sảnh cao trần với hệ đèn thả độc bản, ghế bọc nhung và ô trí đố gỗ.' },
    orientation: 'portrait',
    heroQuality: true,
    roomCardSuitable: false,
  },
  {
    id: 'lob-02',
    filename: 'pexels-misbaa-eri-426041722-36354489.jpg',
    src: '/photos/pexels-misbaa-eri-426041722-36354489.jpg',
    category: 'lobby',
    title: { en: 'Reception Lounge Area', vi: 'Khu Vực Sảnh Lễ Tân' },
    description: { en: 'Curated seating ensemble with mustard accents, wingback chairs, and work desks.', vi: 'Không gian thư giãn kết hợp bàn làm việc và ghế bành thư thái.' },
    orientation: 'portrait',
    heroQuality: false,
    roomCardSuitable: false,
  },

  // 02 — Stone Suites (6 photos)
  {
    id: 'stn-01',
    filename: 'pexels-umudicreative-38183818.jpg',
    src: '/photos/pexels-umudicreative-38183818.jpg',
    category: 'stone',
    title: { en: 'Stone Suite with Hydrotherapy Bath', vi: 'Stone Suite Với Bồn Tắm Thủy Lực' },
    description: { en: 'Exposed stone walls, vaulted wood beam ceiling, panoramic window, and sunken Jacuzzi.', vi: 'Tường đá tự nhiên, trần dầm gỗ, cửa sổ ngắm núi và bồn Jacuzzi.' },
    orientation: 'landscape',
    heroQuality: true,
    roomCardSuitable: true,
  },
  {
    id: 'stn-02',
    filename: 'pexels-umudicreative-38183824.jpg',
    src: '/photos/pexels-umudicreative-38183824.jpg',
    category: 'stone',
    title: { en: 'Panoramic Mountain View Stone Sanctuary', vi: 'Toàn Cảnh Stone Sanctuary Ngắm Núi' },
    description: { en: 'Spacious master suite featuring exposed masonry walls, wooden crib, and Jacuzzi.', vi: 'Phòng Suite rộng lớn với mảng tường đá, nôi gỗ em bé và bồn Jacuzzi.' },
    orientation: 'landscape',
    heroQuality: true,
    roomCardSuitable: true,
  },
  {
    id: 'stn-03',
    filename: 'pexels-umudicreative-38183822.jpg',
    src: '/photos/pexels-umudicreative-38183822.jpg',
    category: 'stone',
    title: { en: 'Stone Suite Lounge Corner', vi: 'Góc Thư Giãn Phòng Stone Suite' },
    description: { en: 'Plush patterned armchairs, polished marble flooring, vanity area, and stone wall backdrop.', vi: 'Bộ ghế armchair hoa văn, sàn đá cẩm thạch bóng và tường đá mộc.' },
    orientation: 'landscape',
    heroQuality: false,
    roomCardSuitable: false,
  },
  {
    id: 'stn-04',
    filename: 'pexels-umudicreative-38183823.jpg',
    src: '/photos/pexels-umudicreative-38183823.jpg',
    category: 'stone',
    title: { en: 'Master Stone Bedroom Details', vi: 'Phòng Ngủ Stone Suite Chi Tiết' },
    description: { en: 'King bed positioned against natural stone masonry with ambient sconce lights.', vi: 'Giường King tựa tường đá tự nhiên cùng đèn ngủ nghệ thuật.' },
    orientation: 'landscape',
    heroQuality: false,
    roomCardSuitable: false,
  },
  {
    id: 'stn-05',
    filename: 'pexels-umudicreative-38183817.jpg',
    src: '/photos/pexels-umudicreative-38183817.jpg',
    category: 'stone',
    title: { en: 'Stone Twin Suite & Open Wardrobe', vi: 'Phòng Stone Twin & Tủ Gỗ Mở' },
    description: { en: 'Twin bed arrangement with open timber shelving, stone walls, and landscape view window.', vi: 'Bố trí 2 giường đơn, hệ kệ gỗ mở, tường đá và cửa sổ nhìn ra núi.' },
    orientation: 'landscape',
    heroQuality: false,
    roomCardSuitable: true,
  },
  {
    id: 'stn-06',
    filename: 'pexels-umudicreative-38183819.jpg',
    src: '/photos/pexels-umudicreative-38183819.jpg',
    category: 'stone',
    title: { en: 'Stone Twin Room Front View', vi: 'Phòng Stone Twin Góc Chính Diện' },
    description: { en: 'Single beds with yellow accent pillows, custom wood headboard, and air conditioning.', vi: 'Giường đơn gối vàng, tựa đầu giường gỗ tự nhiên và tường đá mộc.' },
    orientation: 'landscape',
    heroQuality: false,
    roomCardSuitable: false,
  },

  // 03 — Garden Suites (6 photos)
  {
    id: 'grd-01',
    filename: 'pexels-quang-nguyen-vinh-222549-14025024.jpg',
    src: '/photos/pexels-quang-nguyen-vinh-222549-14025024.jpg',
    category: 'suites',
    title: { en: 'Garden Villa King Suite', vi: 'Phòng Garden Villa King Suite' },
    description: { en: 'Warm teak wall paneling, woven bamboo pendant lamps, and patio opening to tropical garden.', vi: 'Ốp tường gỗ teak ấm áp, đèn mây bọc thủ công và hiên nhìn ra vườn.' },
    orientation: 'landscape',
    heroQuality: true,
    roomCardSuitable: true,
  },
  {
    id: 'grd-02',
    filename: 'pexels-quang-nguyen-vinh-222549-14025032.jpg',
    src: '/photos/pexels-quang-nguyen-vinh-222549-14025032.jpg',
    category: 'suites',
    title: { en: 'Garden Patio & Teak Suite Overview', vi: 'Góc Sân Vườn & Phòng Teak Suite' },
    description: { en: 'Wide perspective of timber room, luggage rack, flat TV, and sliding doors to lush yard.', vi: 'Phòng gỗ rộng rãi với kệ hành lý, TV và cửa trượt ra sân vườn.' },
    orientation: 'landscape',
    heroQuality: true,
    roomCardSuitable: true,
  },
  {
    id: 'grd-03',
    filename: 'pexels-quang-nguyen-vinh-222549-14025037.jpg',
    src: '/photos/pexels-quang-nguyen-vinh-222549-14025037.jpg',
    category: 'suites',
    title: { en: 'Low Angle Garden Villa Bed', vi: 'Góc Thấp Giường Garden Villa' },
    description: { en: 'Pristine white linens with terracotta cushions, bamboo ceiling, and tropical natural light.', vi: 'Drap giường trắng tinh tế, gối đệm màu đất nung và trần mây tre.' },
    orientation: 'landscape',
    heroQuality: false,
    roomCardSuitable: false,
  },
  {
    id: 'grd-04',
    filename: 'pexels-quang-nguyen-vinh-222549-14025022.jpg',
    src: '/photos/pexels-quang-nguyen-vinh-222549-14025022.jpg',
    category: 'suites',
    title: { en: 'Garden Twin Villa Room', vi: 'Phòng Garden Twin Villa' },
    description: { en: 'Twin teak wooden beds with patterned tile inlay flooring and private garden access.', vi: 'Hai giường gỗ đơn trên nền gạch bông hoạ tiết, cửa mở ra vườn.' },
    orientation: 'landscape',
    heroQuality: false,
    roomCardSuitable: true,
  },
  {
    id: 'grd-05',
    filename: 'pexels-quang-nguyen-vinh-222549-14025023.jpg',
    src: '/photos/pexels-quang-nguyen-vinh-222549-14025023.jpg',
    category: 'suites',
    title: { en: 'Garden Twin Detail Angle', vi: 'Chi Tiết Phòng Garden Twin' },
    description: { en: 'Close perspective of handcrafted bamboo lamps, nightstand, and patio greenery.', vi: 'Góc cận đèn mây tre thủ công, tủ đầu giường và cây xanh ngoài hiên.' },
    orientation: 'landscape',
    heroQuality: false,
    roomCardSuitable: false,
  },
  {
    id: 'grd-06',
    filename: 'pexels-quang-nguyen-vinh-222549-14025033.jpg',
    src: '/photos/pexels-quang-nguyen-vinh-222549-14025033.jpg',
    category: 'suites',
    title: { en: 'Garden Suite Entrance Perspective', vi: 'Góc Lối Vào Phòng Garden Suite' },
    description: { en: 'Entrance door opening onto green tropical courtyard, side vanity bar, and ceiling fan.', vi: 'Cửa mở ra sân vườn nhiệt đới, quầy bar nhỏ và quạt trần gỗ.' },
    orientation: 'landscape',
    heroQuality: false,
    roomCardSuitable: false,
  },

  // 04 — Urban Loft (4 photos)
  {
    id: 'urb-04',
    filename: 'pexels-khojiakbar-teshaboev-2154965416-34559240.jpg',
    src: '/photos/pexels-khojiakbar-teshaboev-2154965416-34559240.jpg',
    category: 'urban',
    title: { en: 'City View Executive Studio Bed', vi: 'Giường Ngủ City View Executive Studio' },
    description: { en: 'Vertical shot of king bed with houndstooth throw, geometric carpet, and floor curtain.', vi: 'Góc đứng giường King với chăn houndstooth, thảm hình học và rèm cao kịch trần.' },
    orientation: 'portrait',
    heroQuality: true,
    roomCardSuitable: true,
  },
  {
    id: 'urb-05',
    filename: 'pexels-khojiakbar-teshaboev-2154965416-34618647.jpg',
    src: '/photos/pexels-khojiakbar-teshaboev-2154965416-34618647.jpg',
    category: 'urban',
    title: { en: 'Executive Studio Desk & Console', vi: 'Bàn Làm Việc Executive Studio' },
    description: { en: 'Integrated work desk, flat TV niche, luggage bench, and subtle ambient backlighting.', vi: 'Bàn làm việc, hộc TV âm tường, kệ hành lý và đèn hắt hậu ấm áp.' },
    orientation: 'portrait',
    heroQuality: false,
    roomCardSuitable: false,
  },
  {
    id: 'urb-06',
    filename: 'pexels-khojiakbar-teshaboev-2154965416-34631242.jpg',
    src: '/photos/pexels-khojiakbar-teshaboev-2154965416-34631242.jpg',
    category: 'urban',
    title: { en: 'Window Lounge & City View Angle', vi: 'Góc Thư Giãn Bên Cửa Sổ' },
    description: { en: 'Teal lounge chair, houndstooth ottoman, round coffee table, and city window backdrop.', vi: 'Ghế thư giãn màu xanh ngọc, đôn họa tiết, bàn tròn và khung cửa sổ nhìn ra phố.' },
    orientation: 'portrait',
    heroQuality: false,
    roomCardSuitable: false,
  },
  {
    id: 'urb-07',
    filename: 'pexels-artbovich-7746071.jpg',
    src: '/photos/pexels-artbovich-7746071.jpg',
    category: 'urban',
    title: { en: 'Superior Urban Twin Beds', vi: 'Phòng Superior Urban Twin' },
    description: { en: 'Geometric accent wallpaper, twin single beds, knitted throws, and modern sconce lighting.', vi: 'Giấy dán tường họa tiết hình học, 2 giường đơn và đèn ngủ thiết kế.' },
    orientation: 'landscape',
    heroQuality: false,
    roomCardSuitable: true,
  },

  // 05 — Bedrooms (5 photos)
  {
    id: 'urb-01',
    filename: 'pexels-artbovich-7535007.jpg',
    src: '/photos/pexels-artbovich-7535007.jpg',
    category: 'bedroom',
    title: { en: 'Urban Loft Suite Master Bed', vi: 'Giường King Suite Urban Loft' },
    description: { en: 'Contemporary bedroom with beige upholstered bed, knitted blanket, and modern art prints.', vi: 'Phòng ngủ hiện đại với giường bọc nệm beige, chăn dệt và tranh nghệ thuật.' },
    orientation: 'landscape',
    heroQuality: true,
    roomCardSuitable: true,
  },
  {
    id: 'urb-02',
    filename: 'pexels-artbovich-7535008.jpg',
    src: '/photos/pexels-artbovich-7535008.jpg',
    category: 'bedroom',
    title: { en: 'Urban Loft Dressing & Closet Suite', vi: 'Phòng Thay Đồ Urban Loft Suite' },
    description: { en: 'Integrated dressing system with mirrored wardrobes, plush blue ottoman, and track lighting.', vi: 'Hệ thống phòng thay đồ mở với tủ gương, ghế đôn nhung xanh và đèn ray.' },
    orientation: 'landscape',
    heroQuality: true,
    roomCardSuitable: false,
  },
  {
    id: 'urb-03',
    filename: 'pexels-artbovich-7535013.jpg',
    src: '/photos/pexels-artbovich-7535013.jpg',
    category: 'bedroom',
    title: { en: 'Urban Suite Full Interior Overview', vi: 'Toàn Cảnh Nội Thất Urban Suite' },
    description: { en: 'Expansive open plan layout showcasing walk-in closet, vanity, carpet, and suite bed.', vi: 'Cấu trúc mở rộng rãi bao gồm phòng thay đồ, bàn trang điểm và giường ngủ.' },
    orientation: 'landscape',
    heroQuality: true,
    roomCardSuitable: false,
  },
  {
    id: 'urb-08',
    filename: 'pexels-artbovich-7746077.jpg',
    src: '/photos/pexels-artbovich-7746077.jpg',
    category: 'bedroom',
    title: { en: 'Urban Twin Window & Balcony Angle', vi: 'Góc Ban Công Phòng Urban Twin' },
    description: { en: 'High ceiling twin room with French balcony door, radiator, and tribal pattern ottoman.', vi: 'Phòng twin trần cao với cửa ban công, đôn bọc thổ cẩm và góc đón nắng.' },
    orientation: 'landscape',
    heroQuality: false,
    roomCardSuitable: false,
  },
  {
    id: 'urb-09',
    filename: 'pexels-artbovich-7746082.jpg',
    src: '/photos/pexels-artbovich-7746082.jpg',
    category: 'bedroom',
    title: { en: 'Urban Twin Wardrobe Perspective', vi: 'Tủ Quần Áo Phòng Urban Twin' },
    description: { en: 'White rattan slatted wardrobe, high vaulted ceiling, and geometric wallpaper backdrop.', vi: 'Tủ quần áo cánh đan mây trắng, trần vát cao và mảng tường hoạ tiết.' },
    orientation: 'landscape',
    heroQuality: false,
    roomCardSuitable: false,
  },

  // 06 — Bathrooms (4 photos)
  {
    id: 'bth-01',
    filename: 'pexels-artbovich-6444967.jpg',
    src: '/photos/pexels-artbovich-6444967.jpg',
    category: 'bathrooms',
    title: { en: 'Grey Marble Suite Bathroom with Tub', vi: 'Phòng Tắm Marble Xám & Bồn Tắm' },
    description: { en: 'Floor-to-ceiling grey marble tiles, circular halo mirror, ceramic basin, and glass tub screen.', vi: 'Gạch marble xám kịch trần, gương tròn hắt sáng, chậu rửa sứ và bồn tắm.' },
    orientation: 'landscape',
    heroQuality: true,
    roomCardSuitable: false,
  },
  {
    id: 'bth-02',
    filename: 'pexels-artbovich-6587905.jpg',
    src: '/photos/pexels-artbovich-6587905.jpg',
    category: 'bathrooms',
    title: { en: 'Double Vanity Master Bathroom', vi: 'Phòng Tắm Master Hai Chậu Rửa' },
    description: { en: 'Polished travertine marble, double undermount sinks, large mirror, bidet, and soaking tub.', vi: 'Đá cẩm thạch travertine bóng, 2 chậu rửa, gương lớn, bidet và bồn tắm.' },
    orientation: 'landscape',
    heroQuality: true,
    roomCardSuitable: false,
  },
  {
    id: 'bth-03',
    filename: 'pexels-artbovich-7534212.jpg',
    src: '/photos/pexels-artbovich-7534212.jpg',
    category: 'bathrooms',
    title: { en: 'Contemporary Wood-Tone En-Suite Bath', vi: 'Phòng Tắm Gỗ Hiện Đại En-Suite' },
    description: { en: 'Wood grain tile accents, glass walk-in rain shower, square ceramic basin, and heated towel rack.', vi: 'Ốp gạch vân gỗ, vách tắm kính đứng, chậu rửa hình vuông và giá treo khăn sưởi.' },
    orientation: 'landscape',
    heroQuality: false,
    roomCardSuitable: false,
  },
  {
    id: 'bth-04',
    filename: 'pexels-artbovich-8082553.jpg',
    src: '/photos/pexels-artbovich-8082553.jpg',
    category: 'bathrooms',
    title: { en: 'Executive Suite Rain Shower & Amenities', vi: 'Vách Tắm Đứng & Tiện Nghi Executive' },
    description: { en: 'Frameless glass rain shower, wall-hung bidet and toilet, vanity counter, and laundry unit.', vi: 'Vách tắm đứng kính không viền, bidet treo tường, bàn lavabo gỗ.' },
    orientation: 'landscape',
    heroQuality: false,
    roomCardSuitable: false,
  },
];
